import React, { Component } from 'react'

import Layout from '../../../components/layouts/layout'
import Hero from '../../../components/hero'
import HubspotForm from '../../../components/hubspot-form'
import Image from '../../../components/image'
import Divider from '../../../components/divider'
import References from '../../../components/references'
import Author from '../../../components/author'

import config from '../../../../config'
import { mediaUrl } from '../../../helpers'

const frontmatter = {
  metaTitle: 'Own Your Health Data',
  metaDescription:
    'As the future of our healthcare system moves towards electronic healthcare records, we need patient data ownership rights to protect patient care.',
  heroImage: '/images/features/own-your-health-data/patient-data-ownership.jpg',
}

class OwnYourHealthDataFeature extends Component {
  render() {
    return (
      <Layout frontmatter={frontmatter}>
        <Hero image={frontmatter.heroImage} />
        <div className="determinants-of-health">
          <div className="pad-vertical--double">
            <div className="max-width max-width--md content-padding">
              <h1 className="header--xl">Own Your Health Data</h1>
              <p className="text--grey">
                As the future of our healthcare system moves towards electronic
                healthcare records, we need patient data ownership rights to
                protect patient care.
              </p>

              <h4 className="header--sm">4 Principles</h4>
              <p>
                1. Patients co-own or fully own every health data point about
                themselves.
              </p>
              <p>
                2. Health data generated about the patient by a provider is
                co-owned by both parties.
              </p>
              <p>
                3. Health data generated by the patient is fully owned by the
                patient with a right to possess, share, sell, or destroy.
              </p>
              <p>
                4. All uses of a patients' health data shall be consented in
                advance by the patient, other than uses required by law.
              </p>
            </div>

            <div className="max-width max-width--md content-padding">
              <div className="margin-bottom--double">
                <div className="pure-g button-group margin-bottom">
                  <div className="pure-u-1 pure-u-lg-1-2">
                    <a
                      href="https://github.com/goinvo/OwnYourHealthData/raw/main/OwnYourHealthData_Comic.pdf"
                      target="_blank"
                      rel="noopener noreferrer"
                      className="button button--secondary margin-top--double margin-bottom--half button--block margin-right"
                    >
                      Download Comic
                    </a>
                  </div>
                  <div className="pure-u-1 pure-u-lg-1-2">
                    <a
                      href="https://docs.google.com/document/d/13j03-beeoOZujMK6smdjcicKAb1Jh_L6tn_NG91Nq4M/edit"
                      target="_blank"
                      rel="noopener noreferrer"
                      className="button button--secondary margin-top--double margin-bottom--half  button--block margin-right"
                    >
                      Download Whitepaper
                    </a>
                  </div>
                </div>
              </div>

              <Divider />
            </div>

            <div className="max-width max-width--md content-padding">
              <div className="poster margin-top--double">
                <Image
                  src="/images/features/own-your-health-data/own-your-health-data-comic-cover.jpg"
                  className="image--max-width"
                  sizes={config.sizes.fullInsideMediumMaxWidth}
                />
              </div>
              <div className="button-group">
                <a
                  href="https://github.com/goinvo/OwnYourHealthData/raw/main/OwnYourHealthData_Comic.pdf"
                  target="_blank"
                  rel="noopener noreferrer"
                  className="button button--secondary button--lg margin-top--double margin-bottom button--block"
                >
                  Download Comic
                </a>
              </div>
            </div>
          </div>

          <div className="background--gray pad-vertical--double">
            <div className="max-width max-width--md content-padding">
              <HubspotForm
                formId={config.hubspotNewsletterFullFormId}
                title="Subscribe to our open source healthcare newsletter."
                submitButtonText="Subscribe"
              />
            </div>
          </div>

          <div className="pad-vertical--double">
            <div className="max-width max-width--md content-padding">
              <h2 className="header--lg text--center margin-bottom--half margin-top--double">
                We'd Like Your Feedback
              </h2>
              <p className="text--gray">
                We’ve mapped the most recent available federal, state, and
                relevant private intervention spending to the determinants of
                health. Where data is available, we’ve also compared United
                States performance to a group of comparable countries (OECD
                countries). Explore the poster and references then send your
                feedback on this draft to{' '}
                <a href="mailto:hello@goinvo.com"> hello@goinvo.com</a>
              </p>

              <h4 className="header--sm margin-bottom--half margin-top--double">
                About GoInvo
              </h4>
              <p className="text--gray">
                GoInvo is a healthcare design company that crafts innovative
                digital and physical solutions. Our deep expertise in Health IT,
                Genomics, and Open Source health has delivered results for the
                National Institute of Health, Walgreens, Mount Sinai and
                Partners Healthcare.
              </p>
            </div>
          </div>

          <div className="pad-vertical--double">
            <div className="max-width max-width--md content-padding">
              <div>
                <h2 className="header--xl text--center">Authors</h2>
                <Author name="Annie Lakey Becker" company="-" image="">
                  Bio?
                </Author>
                <Author
                  name="Kim Nipp"
                  company="-"
                  image="/images/features/own-your-health-data/headshot-kim-nipp.jpg"
                >
                  Bio?
                </Author>
                <Author name="Juhan Sonin" company="GoInvo, MIT" />

                <h3 className="header--md">Contributors</h3>

                <p>
                  Eric Benoit
                  <br />
                  Kathy Mikk
                  <br />
                  Harry Sleeper
                </p>
              </div>

              <Divider />

              <div id="references">
                <References
                  references={[
                    {
                      title: 'reference 1',
                      link: '#',
                    },
                  ]}
                />
              </div>
            </div>
          </div>
        </div>
      </Layout>
    )
  }
}

export default OwnYourHealthDataFeature
