import React, { Component } from 'react'

import Layout from '../../../components/layouts/layout'
import Hero from '../../../components/hero'
import HubspotForm from '../../../components/hubspot-form'
import Image from '../../../components/image'
import Divider from '../../../components/divider'
import References from '../../../components/references'
import Author from '../../../components/author'

import config from '../../../../config'
import { mediaUrl } from '../../../helpers'

const frontmatter = {
  metaTitle: 'Own Your Health Data',
  metaDescription:
    'As the future of our healthcare system moves towards electronic healthcare records, we need patient data ownership rights to protect patient care.',
  heroImage: '/images/features/own-your-health-data/patient-data-ownership.jpg',
}

class OwnYourHealthDataFeature extends Component {
  render() {
    return (
      <Layout frontmatter={frontmatter}>
        <Hero image={frontmatter.heroImage} />
        <div className="own-your-health-data">
          <div className="pad-vertical--double">
            <div className="max-width max-width--md content-padding">
              <h1 className="header--xl">Own Your Health Data</h1>
              <p className="text--grey">
                As the future of our healthcare system moves towards electronic
                healthcare records, we need patient data ownership rights to
                protect patient care.
              </p>

              <h4 className="header--sm">4 Principles</h4>
              <p>
                1. Patients co-own or fully own every health data point about
                themselves.
              </p>
              <p>
                2. Health data generated about the patient by a provider is
                co-owned by both parties.
              </p>
              <p>
                3. Health data generated by the patient is fully owned by the
                patient with a right to possess, share, sell, or destroy.
              </p>
              <p>
                4. All uses of a patients' health data shall be consented in
                advance by the patient, other than uses required by law.
              </p>
            </div>

            <div className="max-width max-width--md content-padding">
              <div className="margin-bottom--double">
                <div className="pure-g button-group margin-bottom">
                  <div className="pure-u-1 pure-u-lg-1-2">
                    <div className="poster margin-top--double margin-right margin-left">
                      <a href="https://github.com/goinvo/OwnYourHealthData/raw/main/OwnYourHealthData_Comic.pdf">
                        <Image
                          src="/images/features/own-your-health-data/own-your-health-data-comic-cover-3.jpg"
                          className="image--max-width"
                          sizes={
                            config.sizes.fullToHalfAtLargeInsideMediumMaxWidth
                          }
                        />
                      </a>
                    </div>
                    <a
                      href="https://github.com/goinvo/OwnYourHealthData/raw/main/OwnYourHealthData_Comic.pdf"
                      rel="noopener noreferrer"
                      className="button button--secondary margin-top--double margin-bottom--half button--block margin-right"
                    >
                      Download Comic
                    </a>
                  </div>
                  <div className="pure-u-1 pure-u-lg-1-2">
                    <div className="poster margin-top--double margin-right margin-left">
                      <a
                        href="https://docs.google.com/document/d/13j03-beeoOZujMK6smdjcicKAb1Jh_L6tn_NG91Nq4M/edit"
                        target="_blank"
                      >
                        <Image
                          src="/images/features/own-your-health-data/own-your-health-data-whitepaper-cover.jpg"
                          className="image--max-width"
                          sizes={
                            config.sizes.fullToHalfAtLargeInsideMediumMaxWidth
                          }
                        />
                      </a>
                    </div>
                    <a
                      href="https://docs.google.com/document/d/13j03-beeoOZujMK6smdjcicKAb1Jh_L6tn_NG91Nq4M/edit"
                      target="_blank"
                      rel="noopener noreferrer"
                      className="button button--secondary margin-top--double margin-bottom--half  button--block margin-right"
                    >
                      View Whitepaper
                    </a>
                  </div>
                </div>
              </div>
            </div>
          </div>

          <div className="pad-vertical--double">
            <div className="max-width max-width--md content-padding">
              <h2 className="header--lg text--center margin-bottom--half margin-top--double">
                We'd Like Your Feedback
              </h2>
              <p className="text--gray">
                We've mapped out the needs for owning your health data and have
                illustrated them to be digestible for policy makers and the
                general public. If you have any feedback, please share with{' '}
                <a href="mailto:hello@goinvo.com"> hello@goinvo.com</a>.
              </p>

              <h4 className="header--sm margin-bottom--half margin-top--double">
                About GoInvo
              </h4>
              <p className="text--gray">
                GoInvo is a healthcare design company that crafts innovative
                digital and physical solutions. Our deep expertise in Health IT,
                Genomics, and Open Source health has delivered results for the
                National Institute of Health, Walgreens, Mount Sinai and
                Partners Healthcare.
              </p>
            </div>
          </div>

          <div className="pad-vertical--double">
            <div className="max-width max-width--md content-padding">
              <div>
                <h2 className="header--xl text--center">Authors</h2>
                <p>
                  <strong>Annie Lakey Becker</strong>
                  <br />
                  Annie is a Mom, Product and Project Manager based in Seattle.
                  Passionate about Public Health and systems, her background
                  includes roles as an academic research scientist and
                  patient-focused neurodiagnostic technologist. She has a BS in
                  Public Health from the University of Washington and is
                  completing a Masters in Public Health at UNC Chapel Hill.
                </p>

                <p>
                  <strong>Kim Nipp</strong>
                  <br />
                  Kim is a designer, illustrator, and animator specializing in
                  scientific visualization. Originally trained in behavioural
                  neuroscience at the University of British Columbia, Kim moved
                  on to complete their Masters of Science in Biomedical
                  Communications, an interdisciplinary graduate program for
                  visual media design in science and medicine offered through
                  the Faculty of Medicine at the University of Toronto.
                </p>

                <p>
                  <strong>Juhan Sonin</strong>
                  <br />
                  Juhan Sonin leads GoInvo with expertise in healthcare design
                  and system engineering. He’s spent time at Apple, the National
                  Center for Supercomputing Applications (NCSA), and MITRE. His
                  work has been recognized by the New York Times, BBC, and
                  National Public Radio (NPR) and published in The Journal of
                  Participatory Medicine and The Lancet. He currently lectures
                  on design and engineering at MIT.
                </p>

                <h3 className="header--md">Contributors</h3>

                <p>
                  Eric Benoit
                  <br />
                  Kathy Mikk
                  <br />
                  Harry Sleeper
                </p>
              </div>

              <Divider />

              <div id="references">
                <References
                  references={[
                    {
                      title:
                        'Durcevik, S. 18 Examples of Big Data Analytics in Healthcare That Can Save People. 2020',
                      link:
                        'https://www.datapine.com/blog/big-data-examples-in-healthcare/',
                    },
                    {
                      title:
                        'Price, N. D., Magis, A. T., Earls, J. C., Glusman, G., Levy, R., Lausted, C., McDonald, D. T., Kusebauch, U., Moss, C. L., Zhou, Y., Qin, S., Moritz, R. L., Brogaard, K., Omenn, G. S., Lovejoy, J. C., & Hood, L. (2017). A wellness study of 108 individuals using personal, dense, dynamic data clouds. Nature biotechnology, 35(8), 747–756',
                      link: 'https://doi.org/10.1038/nbt.3870',
                    },
                    {
                      title:
                        'Felitti, V. J., Anda, R. F., Nordenberg, D., Williamson, D. F., Spitz, A. M., Edwards, V., Koss, M. P., & Marks, J. S. (1998). Relationship of childhood abuse and household dysfunction to many of the leading causes of death in adults. The Adverse Childhood Experiences (ACE) Study. American journal of preventive medicine, 14(4), 245–258',
                      link: 'https://doi.org/10.1016/s0749-3797(98)00017-8',
                    },
                    {
                      title:
                        'Magnan S. Social Determinants of Health 101 for Health Care: Five Plus Five. Discussion Paper. October 9, 2017',
                      link:
                        'https://nam.edu/social-determinants-of-health-101-for-health-care-five-plus-five/',
                    },
                    {
                      title:
                        'Liddell, K., Simon, D., & Lucassen, A. Patient Data Ownership: Who Owns Your Health?. Journal of Law and the Biosciences',
                      link: 'https://doi.org/10.17863/CAM.68658',
                    },
                    {
                      title:
                        'Inau, E. T., Sack, J., Waltemath, D., & Zeleke, A. A. (2021). Initiatives, Concepts, and Implementation Practices of FAIR (Findable, Accessible, Interoperable, and Reusable) Data Principles in Health Data Stewardship Practice: Protocol for a Scoping Review. JMIR research protocols, 10(2), e22505',
                      link: 'https://doi.org/10.2196/22505',
                    },
                    {
                      title:
                        ' Beyan, O., Choudhury, A., Van Soest, J., Kohlbacher, O., Zimmermann, L., Stenzhorn, H., Karim, M.R., Dumontier, M., Decker, S., da Silva Santos, L.O., Dekker, A. Distributed Analytics on Sensitive Medical Data: The Personal Health Train. Data Intelligence. 2020 Jan;2(1-2):96–107',
                      link: 'https://doi.org/10.1162/dint_a_00032',
                    },
                    {
                      title:
                        "Mifsud, M., Molines, M., Cases, A. S., & N'Goala, G. (2019). It's MY health care program: Enhancing patient adherence through psychological ownership. Social science & medicine (1982), 232, 307–315",
                      link: 'https://doi.org/10.1016/j.socscimed.2019.05.015',
                    },
                    {
                      title:
                        'Rahimzadeh V. (2021). A Policy and Practice Review of Consumer Protections and Their Application to Hospital-Sourced Data Aggregation and Analytics by Third-Party Companies. Frontiers in big data, 3, 603044',
                      link: 'https://doi.org/10.3389/fdata.2020.603044',
                    },
                    {
                      title:
                        'Kadakia, K. T., Howell, M. D., & DeSalvo, K. B. (2021). Modernizing Public Health Data Systems: Lessons From the Health Information Technology for Economic and Clinical Health (HITECH) Act. JAMA, 326(5), 385–386',
                      link: 'https://doi.org/10.1001/jama.2021.12000',
                    },
                    {
                      title:
                        "Li, L., Novillo-Ortiz, D., Azzopardi-Muscat, N., & Kostkova, P. (2021). Digital Data Sources and Their Impact on People's Health: A Systematic Review of Systematic Reviews. Frontiers in public health, 9, 645260",
                      link: 'https://doi.org/10.3389/fpubh.2021.645260',
                    },
                    {
                      title:
                        'Johnson, C., & Pylypchuck, Y. (2021). Use of Certified Health IT and Methods to Enable Interoperability by U.S. Non-Federal Acute Care Hospitals, 2019',
                      link:
                        'https://www.healthit.gov/sites/default/files/page/2018-12/Methods-Used-to-Enable-Interoperability-among-U.S.-NonFederal-Acute-Care-Hospitals-in-2017_0.pdf',
                    },
                    {
                      title:
                        '243 CMR 2.07(13), Medical Records (Massachusetts) ((a)...A licensee shall maintain a medical record for each patient that is complete, timely, legible, and adequate to enable the licensee or any other health care provider to provider proper diagnosis and treatment....)',
                      link: '',
                    },
                    {
                      title:
                        '105 CMR 130.370 Requirement on Massachusetts hospitals.',
                      link: '',
                    },
                    {
                      title:
                        'George Washington University Health and the Law Project, Who Owns Medical Records: 50 State Comparison (2015)',
                      link:
                        'http://www.healthinfolaw.org/comparative-analysis/who-owns-medical-records-50-state-comparison',
                    },
                    {
                      title:
                        'Evans, B. J. (2011). Much ado about data ownership. Harvard Journal of Law & Technology, 25(1), 69-130.25 Harv. J. L. & Tech. 69 (2011-2012) Much Ado about Data Ownership.',
                      link: '',
                    },
                    {
                      title:
                        'Contreras, J., Health Data Ownership, 94 NYU Law Review 624 (October 2019).',
                      link: '',
                    },
                    {
                      title:
                        'Perzanowski, A., Schultz, J.  The End of Ownership: Personal Property in the Digital Economy. Pub Res Q 34, 154–155 (2018)',
                      link:
                        'https://doi-org.libproxy.lib.unc.edu/10.1007/s12109-018-9567-2',
                    },
                    {
                      title:
                        'McGuire, A. L., Roberts, J., Aas, S., & Evans, B. J. (2019). Who Owns the Data in a Medical Information Commons?. The Journal of law, medicine & ethics : a journal of the American Society of Law, Medicine & Ethics, 47(1), 62–69',
                      link: 'https://doi.org/10.1177/1073110519840485',
                    },
                    {
                      title:
                        'Wakabayashi, D. Google and the University of Chicago Are Sued Over Data Sharing, N. Y. Times, March 26, 2020',
                      link:
                        'https://www.nytimes.com/2019/06/26/technology/google-university-chicago-data-sharing-lawsuit.html (last visited Feb 4, 2020)',
                    },
                    {
                      title:
                        'Bass, D., & Tozzi, J. (2021, February 11). U.S. Health Giants Form Startup to Share, Analyze Patient Data. Retrieved from',
                      link:
                        'https://www.bloomberg.com/news/articles/2021-02-11/startup-truveta-links-u-s-health-systems-to-share-patient-data',
                    },
                    {
                      title:
                        'Ballantyne A. (2020). How should we think about clinical data ownership?. Journal of medical ethics, 46(5), 289–294',
                      link: 'https://doi.org/10.1136/medethics-2018-105340',
                    },
                    {
                      title:
                        'https://www.iab.com/wp-content/uploads/2018/12/IAB_The-State-of-Data-2018_2018-12-05_Final.pdf, see page 5.',
                      link:
                        'https://www.iab.com/wp-content/uploads/2018/12/IAB_The-State-of-Data-2018_2018-12-05_Final.pdf',
                    },
                    {
                      title:
                        'What is an electronic health record (ehr)? HealthIT.gov. (2019, September 10)',
                      link:
                        'https://www.healthit.gov/faq/what-electronic-health-record-ehr',
                    },
                    {
                      title:
                        'Bates, D., Heitmueller, A., Kakad, M., Saria, S. Why policymakers should care about “big data” in healthcare, Health Policy and Technology, Volume 7, Issue 2, 2018, Pages 211-216,ISSN 2211-8837',
                      link: 'https://doi.org/10.1016/j.hlpt.2018.04.006',
                    },
                    {
                      title:
                        'Rodwin, M. A. (2010). Patient data: Property, privacy & the public interest. American Journal of Law & Medicine, 36(4), 586–618',
                      link: 'https://doi.org/10.1177/009885881003600403',
                    },
                    {
                      title:
                        'Olive adopts aws as its preferred cloud provider to create the internet of healthcare. Retrieved August 19, 2021, from',
                      link:
                        'https://www.prnewswire.com/news-releases/olive-adopts-aws-as-its-preferred-cloud-provider-to-create-the-internet-of-healthcare-301353815.html',
                    },
                    {
                      title:
                        "Health Information Privacy Division, O. for C. R. (OCR). (2016, January 5). Individuals' right under hipaa to access their health information. HHS.Gov.",
                      link:
                        'https://www.hhs.gov/hipaa/for-professionals/privacy/guidance/access/index.html',
                    },
                    {
                      title:
                        'Mirchev, M., Mircheva, I., & Kerekovska, A. (2020). The Academic Viewpoint on Patient Data Ownership in the Context of Big Data: Scoping Review. Journal of medical Internet research, 22(8), e22214',
                      link: 'https://doi.org/10.2196/22214',
                    },
                    {
                      title:
                        'Milne, R., Sorbie, A., & Dixon-Woods, M. (2021). What can data trusts for health research learn from participatory governance in biobanks?. Journal of medical ethics, medethics-2020-107020. Advance online publication',
                      link: 'https://doi.org/10.1136/medethics-2020-107020',
                    },
                    {
                      title:
                        'Kostyack P. T. (2002). The emergence of the Healthcare Information Trust. Health matrix (Cleveland, Ohio : 1991), 12(2), 393–447.',
                      link: '',
                    },
                    {
                      title:
                        'Rosenbaum, S. (2010), Data Governance and Stewardship: Designing Data Stewardship Entities and Advancing Data Access. Health Services Research, 45: 1442-1455',
                      link: 'https://doi.org/10.1111/j.1475-6773.2010.01140.x',
                    },
                    {
                      title:
                        'Hibbard, J. H., & Greene, J. (2013). What the evidence shows about patient activation: better health outcomes and care experiences; fewer data on costs. Health affairs (Project Hope), 32(2), 207–214',
                      link: 'https://doi.org/10.1377/hlthaff.2012.1061',
                    },
                  ]}
                />
              </div>
            </div>
          </div>
        </div>
      </Layout>
    )
  }
}

export default OwnYourHealthDataFeature
